#Each new term in the Fibonacci sequence is generated by
#adding the previous two terms. By starting with 1 and 2,
#the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose
#values do not exceed four million, find the sum of
#the even-valued terms.


arr = [1,2]
max = 4000000

# while the last two numbers sum is less than 4 mil, keep adding to array
while arr[-1] + arr[-2] < max
  arr.push(arr[-1] + arr[-2])
end

#find the sum of the even-valued terms
sum = 0
arr.each do |x|
  sum += x if x.even?
end

puts "The sum of the even valued terms is #{sum}."
